# Generated by Django 5.0.4 on 2024-08-18 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_lancador_alter_bid_lances_select_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_lance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lance_watch', to='auctions.listing')),
                ('watch_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_watch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
