# Generated by Django 5.0.4 on 2024-08-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlist_watch_lance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_lance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lance_watch', to='auctions.listing'),
        ),
    ]
