# Generated by Django 5.0.4 on 2024-08-18 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_watch_lance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
