# Generated by Django 5.0.4 on 2024-08-24 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_watch_lance'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lance_maior',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nome_cate',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='auctions.categorie'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imagemURL',
            field=models.URLField(max_length=500, verbose_name='URL da Imagem'),
        ),
    ]
