# Generated by Django 5.0.4 on 2024-08-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_lancador_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
