# Generated by Django 5.0.4 on 2024-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imagemURL',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
    ]
